- name: variables to print
  hosts: web
  vars:
    COURSE: "devops with aws"
    DURATION: "120hrs"
    Trainer: "venkatgopi"
  tasks:
    - name: print the information
      ansible.builtin.debug:
        msg: "Hi, I am learning {{ COURSE }}, duration is: {{ DURATION }}, Trainer: {{ Trainer }}"
