- name: variables to print
  hosts: web
  vars:
    COURSE: "devops with aws"
    DURATION: "120hrs"
    Trainer: "venkatgopi"
  tasks:
    - name: print the information
      ansible.builtin.debug:
        msg: "Hi, I am learning {{ COURSE }}, duration is: {{ DURATION }}, Trainer: {{ Trainer }}"
    - name: print the information agian
      vars:
       COURSE: "devops with awk"
       DURATION: "120hrs"
       Trainer: "venkatgopi"
      ansible.builtin.debug:
        msg: "hi,I am learning {{ COURSE }}, duration is: {{ DURATION}},trainer: {{ Trainer }}"