- name: nginx install and run
  hosts: web
  become: yes
  tasks:
    - name: install nginxx
      ansible.builtin.package:
        name=nginx
        state:present
    - name: run nginx
      ansible.builtin.service:
        name:nginx
        state:started
        enabled:yes



    